### ISSUE TITLE
Implement Milestone

### ISSUE THREAD

**Issue by borkovacd** [borkovacd/tiny-git#8]
- [ ] Create new milestone
- [ ] Update existing milestone
- [ ] Delete existing milestone
- [ ] List project's milestones
